version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
    - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trip_manager
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "32000:3306"
  db_adaptor: 
    image: db_adaptor
    depends_on:
      - db
    links:
      - db
    ports:
      - "5001:5001"


volumes:
  db_data: {}